apiVersion: v1
kind: ServiceAccount
metadata:
  name: officesa
  namespace: office
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portalsa
  namespace: portal

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: office 
subjects:
- kind: ServiceAccount
  name: officesa
  namespace: office
- kind: ServiceAccount
  name: portalsa
  namespace: portal
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: portal
subjects:
- kind: ServiceAccount
  name: officesa
  namespace: office
- kind: ServiceAccount
  name: portalsa
  namespace: portal
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

